apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodezero-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: nodezero
          image: swastiksuman/node-my-server
          ports:
            - containerPort: 3001
